CREATE TYPE "gender_type" AS ENUM (
  'male',
  'female',
  'noSpecify'
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "cpf" VARCHAR NOT NULL,
  "name" VARCHAR NOT NULL,
  "lastname" VARCHAR NOT NULL,
  "gender" gender_type,
  "birthday" DATE,
  "phone" VARCHAR,
  "conditionsTerms" BOOL NOT NULL,
  "email" VARCHAR NOT NULL,
  "password" VARCHAR NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "address" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "postalCode" VARCHAR NOT NULL,
  "street" VARCHAR NOT NULL,
  "houseNumber" VARCHAR NOT NULL,
  "complement" VARCHAR,
  "referencePoint" VARCHAR,
  "country" VARCHAR NOT NULL,
  "state" VARCHAR NOT NULL,
  "city" VARCHAR NOT NULL,
  "nickname" VARCHAR,
  "user_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE
);

CREATE TABLE "product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR NOT NULL,
  "brand" VARCHAR NOT NULL,
  "category" VARCHAR NOT NULL,
  "price" VARCHAR NOT NULL,
  "imgUrl" VARCHAR NOT NULL,
  "saleQtd" INT NOT NULL,
  "description" VARCHAR,
  PRIMARY KEY ("id")
);

CREATE TABLE "bag" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "totalPrice" VARCHAR NOT NULL,
  "user_id" INT NOT NULL,
  "completedPurchase" BOOL NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE
);

CREATE TABLE "productBag" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "quantity" INT NOT NULL,
  "product_id" INT NOT NULL,
  "bag_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("bag_id") REFERENCES "bag" ("id") ON DELETE CASCADE
);

CREATE TABLE "productHistory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "product_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE
);
